# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clai < Formula
  desc ""
  homepage "https://github.com/pteich/clai"
  version "0.1.5"

  on_macos do
    url "https://github.com/pteich/clai/releases/download/v0.1.5/clai_0.1.5_darwin_all.zip"
    sha256 "ee336cdd6514f53d22b5414b56d3465d655ac1e76e9312914d5ffc96831a665d"

    def install
      bin.install "clai"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/clai/releases/download/v0.1.5/clai_0.1.5_linux_amd64.tar.gz"
        sha256 "d00da73fb40e714f81be22fa5693b1eaede095a29b91755a2bfebd29fa4ead2e"

        def install
          bin.install "clai"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/clai/releases/download/v0.1.5/clai_0.1.5_linux_arm64.tar.gz"
        sha256 "cfb6391dbff68a99adfe60fe160bb4855a0f418691c0ccc016f3ead4eba0afa3"

        def install
          bin.install "clai"
        end
      end
    end
  end
end
