# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clai < Formula
  desc ""
  homepage "https://github.com/pteich/clai"
  version "0.2.0"

  on_macos do
    url "https://github.com/pteich/clai/releases/download/v0.2.0/clai_0.2.0_darwin_all.zip"
    sha256 "0e11ec7ef515f6e0beea9e254664a6ba7fd30b0854f6bb961bb7858aae4a610c"

    define_method(:install) do
      bin.install "clai"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/clai/releases/download/v0.2.0/clai_0.2.0_linux_amd64.tar.gz"
      sha256 "ec09fef055b3134f28070516dbcfca48c9c78c7822247b588eedb5bf16bf7d16"
      define_method(:install) do
        bin.install "clai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/clai/releases/download/v0.2.0/clai_0.2.0_linux_arm64.tar.gz"
      sha256 "e2df94f2024409ce21e6ed7983b3fa68980e27d55c45a7159ed47f7e358f6880"
      define_method(:install) do
        bin.install "clai"
      end
    end
  end
end
