# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crdlens < Formula
  desc ""
  homepage "https://github.com/pteich/crdlens"
  version "0.3.2"

  on_macos do
    url "https://github.com/pteich/crdlens/releases/download/v0.3.2/crdlens_0.3.2_darwin_all.zip"
    sha256 "006a10fb2d8e36fdde0360c6a4d683d6b6cda055f8e5ff4503f30f393dcf1974"

    def install
      bin.install "crdlens"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/crdlens/releases/download/v0.3.2/crdlens_0.3.2_linux_amd64.tar.gz"
      sha256 "2effd24e5311bc59699b8354bcd243642458d76b1734cab5d329eb0ffdfd8399"
      def install
        bin.install "crdlens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/crdlens/releases/download/v0.3.2/crdlens_0.3.2_linux_arm64.tar.gz"
      sha256 "0e6d64043205480d285a5ff1f43bc87210f0c12b5786b004851d22a025b2dd05"
      def install
        bin.install "crdlens"
      end
    end
  end
end
