# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crdlens < Formula
  desc ""
  homepage "https://github.com/pteich/crdlens"
  version "0.1.0"

  on_macos do
    url "https://github.com/pteich/crdlens/releases/download/v0.1.0/crdlens_0.1.0_darwin_all.zip"
    sha256 "32615910dbfc5161a7bec65d75e07423ccd28d5633f771a43332a49fe468ec40"

    def install
      bin.install "crdlens"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/crdlens/releases/download/v0.1.0/crdlens_0.1.0_linux_amd64.tar.gz"
      sha256 "4b70be8813d79b62cc0cd9131a51ed9021da298ed514314dbfb0333c92074a50"
      def install
        bin.install "crdlens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/crdlens/releases/download/v0.1.0/crdlens_0.1.0_linux_arm64.tar.gz"
      sha256 "40d3e916aa78234754a629fae718081c8704d643a0669e4d8ff8be91c44c2126"
      def install
        bin.install "crdlens"
      end
    end
  end
end
