# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crdlens < Formula
  desc ""
  homepage "https://github.com/pteich/crdlens"
  version "0.4.0"

  on_macos do
    url "https://github.com/pteich/crdlens/releases/download/v0.4.0/crdlens_0.4.0_darwin_all.zip"
    sha256 "ee8cb9543ba1e9ced4724dfbef05ac0126c08ef019567ec521f087f584819927"

    def install
      bin.install "crdlens"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/crdlens/releases/download/v0.4.0/crdlens_0.4.0_linux_amd64.tar.gz"
      sha256 "9475550132af5e6c30929593f9b9c0a6094c7aa0b1e8b3c7790f0890448d8b6c"
      def install
        bin.install "crdlens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/crdlens/releases/download/v0.4.0/crdlens_0.4.0_linux_arm64.tar.gz"
      sha256 "bfa46d21c8edf4a9477ab72b4aa99190ccf9c6fabef024e0a6b99176aa90d94c"
      def install
        bin.install "crdlens"
      end
    end
  end
end
