# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticQueryExport < Formula
  desc ""
  homepage "https://github.com/pteich"
  version "1.6.2-test"

  on_macos do
    url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.2-test/elastic-query-export_1.6.2-test_darwin_all.zip"
    sha256 "e5f324e72622c4d63adfe8f35aa61c61d33c7686822060f36ac998c032512634"

    def install
      bin.install "elastic-query-export"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.2-test/elastic-query-export_1.6.2-test_linux_amd64.tar.gz"
        sha256 "ea22c69e3ebf14a1f803385ea35ba6259407896c8a4b401a9e98b2207da6ec04"

        def install
          bin.install "elastic-query-export"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.2-test/elastic-query-export_1.6.2-test_linux_arm64.tar.gz"
        sha256 "5fe4bb62e6f9beadb5a672b88dfb6abab8872e6e23fec2cab76561f81cadfb31"

        def install
          bin.install "elastic-query-export"
        end
      end
    end
  end
end
