# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticQueryExport < Formula
  desc ""
  homepage "https://github.com/pteich/elastic-query-export"
  version "1.6.3"

  on_macos do
    url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.3/elastic-query-export_1.6.3_darwin_all.zip"
    sha256 "12cbbf71a3aea8201c786b4b081654a2674ef6aafadf7945d8c8963d71386f51"

    def install
      bin.install "elastic-query-export"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.3/elastic-query-export_1.6.3_linux_amd64.tar.gz"
        sha256 "fb56d34c7459f7bb7fb01f0fab45ea742b156b26f0b6b840c4836efd077ec93a"

        def install
          bin.install "elastic-query-export"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.3/elastic-query-export_1.6.3_linux_arm64.tar.gz"
        sha256 "e879babab3fb0762c8729e7ca6393bedb84faf2d07857fa588bee1056a2037ba"

        def install
          bin.install "elastic-query-export"
        end
      end
    end
  end
end
