# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticQueryExport < Formula
  desc ""
  homepage "https://github.com/pteich"
  version "1.6.2-test"

  on_macos do
    url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.2-test/elastic-query-export_1.6.2-test_darwin_all.zip"
    sha256 "dd3c80b0f448e4487c72e69a6b10a55c594c4ef07f61ac82d08ad2cbe968f6a9"

    def install
      bin.install "elastic-query-export"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.2-test/elastic-query-export_1.6.2-test_linux_amd64.tar.gz"
        sha256 "25160c042cdb68f963283fc827aed81ba62bbc1f02196510ed8ddb6367e4351d"

        def install
          bin.install "elastic-query-export"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pteich/elastic-query-export/releases/download/v1.6.2-test/elastic-query-export_1.6.2-test_linux_arm64.tar.gz"
        sha256 "e60127d1e3fd3e09230f77e68d0aec5805366a083c83c0873a4b67b8cd518ad8"

        def install
          bin.install "elastic-query-export"
        end
      end
    end
  end
end
