# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcplens < Formula
  desc ""
  homepage "https://github.com/pteich/kcplens"
  version "0.1.0"

  on_macos do
    url "https://github.com/pteich/kcplens/releases/download/v0.1.0/kcplens_0.1.0_darwin_all.zip"
    sha256 "4297da5433b769367d8e937c887ead4c6ca79fd48f0077786d79a2662d547112"

    def install
      bin.install "kcplens"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/kcplens/releases/download/v0.1.0/kcplens_0.1.0_linux_amd64.tar.gz"
      sha256 "204635c6db480247d6ff27f08234db1fe66fb5a9d1f12057a0ac412fcadbbf92"
      def install
        bin.install "kcplens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/kcplens/releases/download/v0.1.0/kcplens_0.1.0_linux_arm64.tar.gz"
      sha256 "a2eb598458c0d467a1b8022263bfd53bb7bbf0e2e7d4895b2b0ff401304b794d"
      def install
        bin.install "kcplens"
      end
    end
  end
end
