# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcplens < Formula
  desc ""
  homepage "https://github.com/pteich/kcplens"
  version "0.2.0"

  on_macos do
    url "https://github.com/pteich/kcplens/releases/download/v0.2.0/kcplens_0.2.0_darwin_all.zip"
    sha256 "6dd79656717fbec4d542d9330ddeb620a509d9467f819ee9f906013902d00f3f"

    def install
      bin.install "kcplens"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/kcplens/releases/download/v0.2.0/kcplens_0.2.0_linux_amd64.tar.gz"
      sha256 "d6ea3e2bc1630e87374735705eb4510a0123c7957355c0ce88d2bccd45d47759"
      def install
        bin.install "kcplens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/kcplens/releases/download/v0.2.0/kcplens_0.2.0_linux_arm64.tar.gz"
      sha256 "fe2699f7f134d98a28c727e355b29d38ad154e6b2a6a00eb0490d8ac2eca0ff8"
      def install
        bin.install "kcplens"
      end
    end
  end
end
