# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoHopper < Formula
  desc ""
  homepage "https://github.com/pteich/repo-hopper"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.1/repo-hopper-cli_darwin_amd64.tar.gz"
      sha256 "e7211ae0bb7f677d525e13eb79f9a04d85d334f50282414387d97dde8eebcf77"

      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.1/repo-hopper-cli_darwin_arm64.tar.gz"
      sha256 "966148cc3a6a63e7ac46b585021ad0fd41aa4c88107c92732c0f3d14f7aaf221"

      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.1/repo-hopper-cli_linux_amd64.tar.gz"
      sha256 "158fe7b818cfece5455a64065167920aade975751f783eb4037d3bbbdc1bcd8d"
      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.1/repo-hopper-cli_linux_arm64.tar.gz"
      sha256 "361aac1ab8123bbba3f42d1d6b271f1a5df92208998dced16d184500ef27246f"
      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
  end
end
