# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoHopper < Formula
  desc ""
  homepage "https://github.com/pteich/repo-hopper"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.0/repo-hopper-cli_darwin_amd64.tar.gz"
      sha256 "ab00e9a62db8382cc2298e2594257fac5b6102b1bc08feecea6941955cb17673"

      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.0/repo-hopper-cli_darwin_arm64.tar.gz"
      sha256 "4d398b1c3c2c022fb19151691be59c8db529fe1c9faa585bf63917a59ab09c72"

      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.0/repo-hopper-cli_linux_amd64.tar.gz"
      sha256 "8a6a2ca2575b99eafb0529b9ceffc5cef60e2ff819c7039ed60b819b7d490769"
      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pteich/repo-hopper/releases/download/v0.2.0/repo-hopper-cli_linux_arm64.tar.gz"
      sha256 "f4dc70a79601093cf85a56b23f46253945ca573b1ff25f627cf08de253d02024"
      define_method(:install) do
        bin.install "repo-hopper"
      end
    end
  end
end
